spring:
  main:
    web-application-type: none
  config:
    import: "optional:configtree:/mnt/secrets/disposer/"
  application:
    name: Fee and Pay Disposer

azure:
  application-insights:
    instrumentation-key: ${disposer.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

service:
  enabled: ${DISPOSER_FEE_PAY_ENABLED:false}
