spring:
  main:
    web-application-type: none
  config:
    import: "optional:configtree:/mnt/secrets/disposer/"
  application:
    name: Fee and Pay Disposer

azure:
  application-insights:
    instrumentation-key: ${disposer.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

service:
  enabled: ${DISPOSER_FEE_PAY_ENABLED:false}

idam:
  s2s-auth:
    name: ${S2S_NAME:disposer-fee-and-pay}
    url: ${S2S_URL:http://localhost:4502}
    secret: ${S2S_SECRET_DISPOSER_FEE_AND_PAY:AAAAAAAAAAAAAAAA}
