server:
  port: 4550
  shutdown: "graceful"

# If you use a database then uncomment the `group:, readiness: and include: "db"` lines in the health probes and uncomment the datasource section
management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  config:
    import: "optional:configtree:/mnt/secrets/disposer/"
  application:
    name: Fee and Pay Disposer

azure:
  application-insights:
    instrumentation-key: ${disposer.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
